server:
  port: 8101
spring:
  application:
    name: hystrix-server-c
# 注册中心eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxyStreamAllowList:
      - "localhost"