server:
  port: 8783
# 配置注册中心地址
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
# 配置应用名称
spring:
  application:
    name: order-service
# 开启  feign的  hystrix支持
feign:
  hystrix:
    enabled: true
