server:
  port: 8093
spring:
  application:
    name: goods-server
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.231.146:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678