spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/vcharfred/config-cloud
#          username: \u8D26\u53F7
#          password: \u5BC6\u7801
server:
  port: 9100
# \u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
