server:
  port: 9000
spring:
  application:
    name: api-getway-zuul
# 配置注册中心地址
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    order-service: /openapi/**
    # 忽略某些服务不对外提供
    #ignored-services: order-service
    # 通过正则表达式匹配，来屏蔽服务的直接访问；这样就只能使用apigetway提供的服务
    #ignored-patterns: /*-service/**
#  sensitive-headers: