server:
  port: 8082
spring:
  application:
    name: rocketmq-client-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
rocketmq:
  name-server: 192.168.111.53:9876
  producer:
    group: client-server
  consumer:
    - consumerGroup: simple-message
      consumeFromWhere: CONSUME_FROM_LAST_OFFSET
      topics: pay-info
      rocketConsumerHandler: "top.vchar.rocketmq.config.rocketmq.handler.SimpleRocketConsumerHandler"
    - consumerGroup: order-message
      topics: order-notify
      number: 1
      type: 1
    - consumerGroup: transaction-message
      topics: activity-notify
      number: 3
