server:
  port: 8100
  tomcat:
    # 线程池配置
    threads:
      # 最大链接数
      max: 5
    # 最大等待数
    accept-count: 0
    # 最大链接数：这个参数是指在同一时间，tomcat能够接受的最大连接数。一般这个值要大于maxThreads+acceptCount
    max-connections: 6

spring:
  application:
    name: hystrix-server-a
# 注册中心eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 20000
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxyStreamAllowList:
      - "localhost"
  command:
    default:
      execution:
        isolation:
          # 隔离模式：线程池隔离
          strategy: THREAD
          thread:
            # 线程超时时间，单位毫秒
            timeoutInMilliseconds: 1000
            # 设置HystrixCommand.run()的执行是否在超时发生时被中断
            interruptOnTimeout: true
        semaphore:
          # 流量阀值
          maxConcurrentRequests: 10
        timeout:
          # 超时是否开启
          enabled: true
      circuitBreaker:
        # 短路器是否开启
        enabled: true
        # 熔断触发最小请求次数
        requestVolumeThreshold: 20
        # 熔断后休眠多久，单位毫秒
        sleepWindowInMilliseconds: 5000
        # 触发熔断错误的比例阀值
        errorThresholdPercentage: 50