server:
  port: 8100
spring:
  application:
    name: hystrix-server-a
# 注册中心eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true