server:
  # 设置端口号
  port: 8080
  servlet:
    # 配置部署的路径
    context-path: /
spring:
  thymeleaf:
    # 本地开发关闭缓存
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
  resources:
    static-locations: