server:
  # 设置端口号
  port: 8080
  servlet:
    # 配置部署的路径
    context-path: /
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    # 集群配置
    #broker-url=failover:(tcp://localhost:61616,tcp://localhost:61617)
    user: admin
    password: admin
    # 配置连接池
    pool:
      enabled: true
      max-connections: 100
#  jms:
##     开启发布订阅模式
#    pub-sub-domain: true