spring:
  redis:
    # 链接地址
    host: 127.0.0.1
    # 认证密码
    password: 123456
    # 数据库序号
    database: 0
    # 链接超时，单位毫秒
    timeout: 2000
    # 这个比jedis性能更好
    lettuce:
      pool:
        # 池中最大活跃数，-1表示不限制
        max-active: 10
        # 池中最小空闲链接
        min-idle: 1
        # 池中最大空闲链接
        max-idle: 8
        # 最大等待时间，单位毫秒，-1表示不限
        max-wait: 1000


