server:
  # 设置端口号
  port: 8080
  servlet:
    # 配置部署的路径
    context-path: /
apache:
  rocketmq:
    consumer:
      push-consumer: orderConsumer
    producer:
      producer-group: orderProducer
    namesrv-addr: 127.0.0.1:9876

