server:
  port: 8091
spring:
  application:
    name: dubbo-customer-demo
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.102:8848
dubbo:
  registry:
    address: spring-cloud://192.168.56.102
  cloud:
    subscribed-services: dubbo-provider-demo