server:
  port: 8091
spring:
  application:
    name: dubbo-customer-demo
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://192.168.56.1
  cloud:
    subscribed-services: dubbo-provider-demo