server:
  port: 8090
spring:
  application:
    name: dubbo-provider-demo
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.102:8848
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://192.168.56.102
  scan:
    base-packages: top.vchar