server:
  port: 8081
spring:
  application:
    name: eureka-client-a
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
# 注册中心eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/