server:
  port: 8781
# 配置注册中心地址
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
# 配置应用名称
spring:
  application:
    name: order-service
# 自定义策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule